### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by SadashayKanungo** [scorelab/NFT-Toolbox#13]
### Description
Create a User Guide with graphics and examples

### Impact
> User Guide added

**Comment by Hyperion101010** [comment]
hi, @AbhiKul10 @SadashayKanungo I wanted to have a look at the project plan and systems design docs.
Can you guide me where to look?
I am a Nodejs developer enthusiast about nft and web3, wanted to contribute for this.

**Comment by SadashayKanungo** [comment]
Hi @Hyperion101010 , 
This package is in initial development phase. You can expect the first release along with documentation and developer guide by the end of this month. In the mean time you can follow the project progress on [Medium](https://medium.com/@sadashay). Feel free to join the community chat on [Gitter](https://gitter.im/scorelab/mint-NFT).
